<?php

return [
    "spaces" => [
        "DIGITALOCEAN_SPACES_KEY" => env("DIGITALOCEAN_SPACES_KEY"),
        "DIGITALOCEAN_SPACES_SECRET" => env("DIGITALOCEAN_SPACES_SECRET"),
        "DIGITALOCEAN_SPACES_ENDPOINT" => env("DIGITALOCEAN_SPACES_ENDPOINT"),
        "DIGITALOCEAN_SPACES_REGION" => env("DIGITALOCEAN_SPACES_REGION"),
        "DIGITALOCEAN_SPACES_BUCKET" => env("DIGITALOCEAN_SPACES_BUCKET"),
    ],
];
