<?php

use GuzzleHttp\RequestOptions;
use Spatie\Sitemap\Crawler\Profile;

return [
    "MAGNIFINANCE_PASSWORD" => env('MAGNIFINANCE_PASSWORD'),
    "MAGNIFINANCE_API_BASE_URL" => env('MAGNIFINANCE_API_BASE_URL'),
    "MAGNIFINANCE_TOKEN" => env('MAGNIFINANCE_TOKEN'),
    "MAGNIFINANCE_USER" => env('MAGNIFINANCE_USER'),
    "MAGNIFINANCE_BO_PANEL_URL" => env('MAGNIFINANCE_BO_PANEL_URL'),
];
